### PR TITLE
Remove remnants of react-notification-system

### LINKED ISSUE #1000: react-notification-system and react
### Is your feature request related to a problem? Please describe.

react-notification-system has peerDependencies of React 16 and less. OED now uses React 17. To fix, installOED.sh added --legacy-peer-deps (see TODO). The issue is that this affects all packages.

### Describe the solution you'd like

react-notification-system does not seem to have updates in the past few years. We should see if they do updates for more recent versions of React. Alternative is to find another package that would work for our needs in OED.

### Describe alternatives you've considered

The hack listed above is what was used.

### Additional context

none

### PR DESCRIPTION
**Pull request by spearec**
# Description

As part of the work in migrating to React 18, we switched from `react-notification-system` to the newer `react-toastify`. Some remnants of the old package were not removed. I should have removed all references, but if there's anything I have missed feel free to add a commit to this PR to remove them.

Due to this old package, we were building OED's dependencies with `--legacy-peer-deps`. This is no longer required, so I have regenerated `package-lock.json` using `npm i`. This should optimize the dependency tree for a regular install.

It also seems that the package-lock had a version tag of 0.8.0, so the regeneration updated that as well.

Fixes #1000 

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

### CODE REVIEW

**Comment by huss** [comment]
Thanks @spearec for doing this. I had a question. package-lock.json has a lot of changes and more than I would expect from just removing the one package. Was a full install done? Did you want to include all these changes in this PR? I want to be sure it does what is intended and it is noted.

**Comment by spearec** [comment]
Yes, I deleted the package-lock and recreated it with `npm i`. This is because, to my understanding, building with the legacy peer deps flag can create a different package lock tree. I can do some more research to make sure.

**Comment by huss** [comment]
I looked over the package changes and they are mostly minor updates. I planned to begin package upgrades soon so this seems fine. Modest testing found no issues so I think these changes are fine. We also have lots of time to see if any small issues are found.

**Review by huss — APPROVED** [review]
Thanks to @spearec for doing this. Everything seems fine.

**Comment by spearec** [comment]
Yeah, the only things that changed from the package lock would be peer dependencies, so there shouldn't be any issues.

**Pull request merged**
