### PR TITLE
Implemented TestB10 from testing.md in DesignDocs

### PR DESCRIPTION
**Pull request by JaedonSpurlock01**
# Description

Team created Test B10 in Issue #[962](https://github.com/OpenEnergyDashboard/OED/issues/962)

Implemented by: @Karti722 @zhufangu @JaedonSpurlock01

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [ ] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

None

### CODE REVIEW

**Comment by JaedonSpurlock01** [comment]
The readingUtils.js was restored back to file as presented in the main OED repository, which is why it shows those massive changes in this pull request.

**Comment by huss** [comment]
> The readingUtils.js was restored back to file as presented in the main OED repository, which is why it shows those massive changes in this pull request.

@JaedonSpurlock01 From what I see, the changes in this file are formatting where a new space was added to each line. I fix these in Visual Studio Code by formatting the file. You are welcome to do this or you can let me know that you want me to fix it.

**Comment by JaedonSpurlock01** [comment]
@huss You are welcome to do as needed for the formatting, thank you!

**Review by huss — APPROVED** [review]
Thanks to @Karti722, @zhufangu & @JaedonSpurlock01 for their first contribution to OED. A code review found no issues with the latest version and it runs as expected. Congratulations on your first accepted work for OED.

**Pull request merged**
