### PR TITLE
Add admin preference to hide chart options

### PR DESCRIPTION
**Pull request by johndiiorio**
Implements #244 

This should not probably not be merged until after TypeScript goes through.

### CODE REVIEW

**Comment by simonbtomlinson** [comment]
Let's make sure we merge typescript first. Merging this into the typescript branch would be really awful.

**Comment by simonbtomlinson** [comment]
Don't we want a button to change this for a single page load, not a server-wide change? It seems like turning this on makes the site really unintuitive for the vast majority of users.

**Comment by NoraCodes** [comment]
Yeah, I think this is honestly not a good way to implement this. For the "wall display" use case, we could just set a cookie or localStorage value and check it.

**Comment by johndiiorio** [comment]
Superseded by #331

**Pull request closed without merging**
