### PR TITLE
Test L20 Implementation

### PR DESCRIPTION
**Pull request by ngocvbh**
# Description

Implemented test L20 with description: "should have daily points for 15 minute reading intervals and quantity units with +-inf start/end time & kWh as lbs of CO2 & chained & reversed."

Co-authored By: @aaronlhh, @SirKentut, and @ObtuseGooose.

Partly Addresses [#962](https://github.com/OpenEnergyDashboard/OED/issues/962).

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

### CODE REVIEW

**Review by huss — CHANGES_REQUESTED** [review]
Thanks to @aaronlhh, @SirKentut and @ObtuseGooose for their (first, I believe) contribution to OED. Review of the code and testing found it works as expected. One small item. The expected file has fewer digits of accuracy than the one on the Design Docs. I think it would be good if they agree so the one in this pull request is replaced with the one on the Design Doc. Once that is done this should be ready to merge.

**Comment by ngocvbh** [comment]
Hello @huss, thank you for reviewing our contribution! I just want to make sure I understand your change request correctly, do I revert the changes I made to the expected file?

**Comment by huss** [comment]
> Hello @huss, thank you for reviewing our contribution! I just want to make sure I understand your change request correctly, do I revert the changes I made to the expected file?

@ngocvbh Since the values I see before the PR were wrong (there was an issue with the values that the new expected file has fixed), I'm not sure reverting your changes will work. You can copy the version from Design Docs to replace the one you have so they are the same. That should work. If you prefer, I can make the change but wanted to give you the opportunity. If this is not clear then please let me know.

**Comment by ngocvbh** [comment]
@huss Thank you for your clarification! I have updated the expected file to match with the one in Design Docs.

**Review by huss — APPROVED** [review]

**Pull request merged**
