### PR TITLE
Units test

### PR DESCRIPTION
**Pull request by rriicc00**
# Description

This pull request adds testing to Unit routes. Contributors are @rriicc00 @softTam @nghiapham1026 

This work is consistent with issue #698.

## Type of change

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [X] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [X] I have removed text in ( ) from the issue request

## Limitations

Might be valuable to test other unit routes.

### CODE REVIEW

**Comment by huss** [comment]
I merged in development to make sure all was okay since I just merged a PR to fix the GitHub action tests and this PR involves tests. It worked fine (as expected).

**Review by huss — APPROVED** [review]
I thank  @rriicc00 @softTam @nghiapham1026 for their first PR. The review found no issues and it works as expected. Good work.

**Comment by nghiapham1026** [comment]
Dear Steve,

That sounds great. Again, thank you very much for the experience you've
given us in the past month.

Best Regards,
Nathan Pham

**Comment by softTam** [comment]
Dear Steve,

Thank you for letting us know that our PR has been merged. And thanks again
for providing us mentorship during this Micro-Internship.

Best regards,
Tam Nguyen



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/31/22,
05:46:48 PM

**Pull request merged**
