### PR TITLE
TODO comment removal and alterations as requested (Issue #592)

### LINKED ISSUE #592: figure out TODO items in code
The OED code base has TODO comments. We need to find them all, see if they are important, see if issues exist as appropriate or they need to be created.

### PR DESCRIPTION
**Pull request by vladoleksiyenko**
# Description

Removed several TODO comments that weren't needed, added more info to a TODO comment, changed a TODO to Note, as requested (Issue #592)

Fixes #592

## Collaborators
- Matt Miss @MattMiss
- Vlad Oleksiyenko @vladoleksiyenko
- Brandon Viorato @brandonviorato
- Eugene Faison @Gene7Him

## Type of change

- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.org/developer/cla/) and each author is listed in the Description section.

Reference to DesignDoc PR:
https://github.com/OpenEnergyDashboard/DesignDocs/pull/4

### CODE REVIEW

**Comment by huss** [comment]
For the record: I added back one of the comments and edited so for v2.0 not v1.1. I was not clear in what I was asking for so I fixed it up.

**Review by huss — CHANGES_REQUESTED** [review]
Thanks to @MattMiss, @vladoleksiyenko, @brandonviorato & @Gene7Him for addressing this issue. This looks good. Note the GitHub integration  test failed because there are trailing spaces on some comment lines in ReadingsCSVUploadComponent.tsx. Would you like to fix this?

**Comment by vladoleksiyenko** [comment]
Sorry about that, I'll get that issue fixed.

**Comment by vladoleksiyenko** [comment]
I've committed and pushed an update that should fix those trailing whitespaces.

**Review by huss — APPROVED** [review]

**Pull request merged**
