### PR TITLE
test B5

### PR DESCRIPTION
**Pull request by kaito1105**
# Description

- Implemented test case B5 with description: "75 day bars for 15 minute reading intervals and quantity units with +-inf start/end time & kWh as kWh"
- Uploaded appropriate CSV file for expected values.

Co-authored by: @SebastianRamos3, and @avery-belmont

Partly Addresses #962

## Type of change

- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

### CODE REVIEW

**Comment by huss** [comment]
@kaito1105 Thank you for you contribution to OED. Please follow the [directions for a PR](https://openenergydashboard.github.io/developer/pr.html). If nothing else, please check the box indicating every contributor has signed the CLA and the names are listed in the description. Please let me know if you have any questions or concerns.

**Review by kaito1105 — COMMENTED** [review]
Added Test B5 and appropriate CSV file.

**Comment by huss** [comment]
I have three questions about CLA agreements:

1. @kaito1105 created the PR
2. @avery-belmont is listed as contributing to the PR in the description
3. Maryam Bouamama is listed as contributing to the commit

In each case I cannot find a record of these people agreeing to the OED CLA. Given the record, it appears each of these people need to sign the CLA. If I have missed something in the record of CLA agreements or you have any thoughts then please let me know. Otherwise, OED needs the CLA agreements before this work can be accepted.

**Comment by avery-belmont** [comment]
May you please send me the CLA agreement? Also, @avery-belmont is me,
Maryam Bouamama. Thank you!

**Comment by huss** [comment]
[@avery-belmont](https://github.com/avery-belmont) For the CLA, please see https://openenergydashboard.github.io/developer/cla.html.

**Comment by avery-belmont** [comment]
Completed!

**Comment by huss** [comment]
Thanks to @kaito1105, @SebastianRamos3 & @avery-belmont for their first contribution to OED. Review found the code is fine and it runs as desired. This PR will be ready to merge once the CLA question with @kaito1105 is resolved.

**Review by huss — APPROVED** [review]
Per the comments, this PR is ready to merge.

**Pull request merged**
