### PR TITLE
Added Test Case BG16

### PR DESCRIPTION
**Pull request by MatthewTran22**
# Description

Added Test Case BG16 into readingsBarGroupFlow.js

Partially Addresses #962 

Co-Authors:
@darvr1
@suchithgali

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

None of Test Case BG16

### CODE REVIEW

**Review by huss — COMMENTED** [review]
Thanks to @MatthewTran22, @darvr1 & @suchithgali for their first contribution to OED. Review and testing found it works as expected. This is only a comment since my records do not indicate that @darvr1 has signed the OED CLA (See https://openenergydashboard.org/developer/cla/) but the box is checked above. Please let me know if you think my records are off. Once this is resolved the code should be able to merge.

**Comment by darvr1** [comment]
I re-signed the OED CLA. Please check again, and let me know if everything looks good. Thank you for your patience.

**Comment by huss** [comment]
> I re-signed the OED CLA. Please check again, and let me know if everything looks good. Thank you for your patience.

Thanks for doing the CLA. All is good.

**Review by huss — APPROVED** [review]
Everything looks good. Congratulations to @MatthewTran22, @darvr1 & @suchithgali  for their first accepted contribution to OED.

**Pull request merged**
