### PR TITLE
Added Spanish and fixed up Languages

### PR DESCRIPTION
**Pull request by pathik10**
I have not made a change to to the menu to select languages as I cannot login and I couldn't see on my machine if it broke anything or not.

### CODE REVIEW

**Comment by corralem** [comment]
I reviewed the Spanish translations. Made a lot of changes. I will need to see original English phrases for some of the sentences. 
[data.json.txt](https://github.com/OpenEnergyDashboard/OED/files/4620105/data.json.txt)

**Comment by huss** [comment]
For @corralem: The English phrases are at the top of the file in the code base and are in the data.json.txt file you linked. Let me know if you need help.

**Comment by corralem** [comment]
Fully revised Spanish translations
[data.json.txt](https://github.com/OpenEnergyDashboard/OED/files/4625684/data.json.txt)

**Comment by huss** [comment]
The changes have been reviewed with some changes made. The code passes all local checks.

Changing the language to Spanish on the admin page does not permanently (after a refresh) store the change. This needs to be resolved before merging.

**Review by huss — APPROVED** [review]
The issue with not keeping Spanish was not yet having updated my development DB to have 'es' in the proper enum. Everything now works fine.

**Comment by huss** [comment]
This PR has been updated so it now address issues #468 and #459.

**Pull request merged**
