### PR TITLE
Update to TypeScript 3.0, and some other package updates.

### PR DESCRIPTION
**Pull request by NoraCodes**
Addresses. but does not finish, #167

### CODE REVIEW

**Comment by huss** [comment]
The changes seem okay but I'm wondering why Travis is reporting an error.

**Comment by shuheif** [comment]
I'm not sure if it relates to the Travis error but I'm getting other errors as below when starting the app. I'm checking the code for compare graph to see what the issue is.
```
ERROR in [at-loader] ./src/client/app/containers/CompareChartContainer.ts:171:41 
    TS2345: Argument of type 'typeof Bar' is not assignable to parameter of type 'ComponentType<LinearComponentProps & DispatchProp<any> & CompareChartContainerProps>'.
  Type 'typeof Bar' is not assignable to type 'StatelessComponent<LinearComponentProps & DispatchProp<any> & CompareChartContainerProps>'.
    Type 'typeof Bar' provides no match for the signature '(props: LinearComponentProps & DispatchProp<any> & CompareChartContainerProps & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.

ERROR in [at-loader] ./node_modules/@types/react-bootstrap/index.d.ts:20:55 
    TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
```

**Comment by NoraCodes** [comment]
The Travis build failed because `npm install` took too long.

**Comment by shuheif** [comment]
Those two errors I mentioned above were because of my local environment. So, the code should be good. I'm sorry. Also, I don't know why `npm install` took so long for this whereas it worked fine for #346.

**Comment by shuheif** [comment]
Updated some more packages to fix security vulnerabilities. One of them fixes `TS2344: Type 'keyof T' does not satisfy the constraint 'string'` error, but `TS2345: Argument of type 'typeof Bar' is not assignable to parameter of type 'ComponentType<LinearComponentProps & DispatchProp<any> & CompareChartContainerProps>'` is still there. Also, I'm wondering why the Travis test did not work for the push.

**Comment by shuheif** [comment]
Thank you, Leo! It passes the Travis test and has no problem as far as I run it in the dev mode.

**Comment by NoraCodes** [comment]
@shuheif Could you approve this? I'd like to merge it

**Review by shuheif — APPROVED** [review]

**Pull request merged**
