### PR TITLE
Chart bar and line related

### LINKED ISSUE #578: chart link not working for bar graphs
If you try to use the chart link it causes a promise error in the console and you don't see any graphic.

### LINKED ISSUE #580: chart link bad if resize line graphic
If you change the date range on the line graphic and redraw, the link can look something like this:
http://localhost:3000/graph?meterIDs=1,2&chartType=line&serverRange=2020-04-06T17:42:30Z_Invalid date&serverRange=2020-04-06T17:42:30Z_Invalid date&sliderRange=all
or
http://localhost:3000/graph?meterIDs=1&chartType=line&serverRange=2020-04-19T08:53:06Z_2020-09-30T23:24:59Z&serverRange=2020-04-19T08:53:06Z_2020-09-30T23:24:59Z&sliderRange=all
so sometimes it has an Invalid date but not always and this does not seem to matter. It also seems that sometimes you get more than two serverRange values. If you try to use this chart link then you seem to get two promise issues and a blank graphic. If you try to continue using the web page that you used the chart link the problems occur. For example, going to the map graph no longer shows the meters. There might be other issues too. This does not seem to impact other web browser windows using OED.

### PR DESCRIPTION
**Pull request by ngan-cassie**
# Description

- Change the time reading/ bar duration of the bar graph down by 1 day.
- Add comments to the changes. 
- Fix the promise error when pasting bar chart link.
- Fix time reading for line chart.

Fixes #578 and fixes #580 
Partly addresses #477. The line case was partially addressed. This fixes the bar case and the group meter for line. Compare remains.

## Type of change

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

### CODE REVIEW

**Review by huss — CHANGES_REQUESTED** [review]
Everything look good and testing found no issues. I only note that the fix for the x-axis date/time for groups that was also fixed in  src/client/app/containers/LineChartContainer.ts  about line 97 in PR #675  is not in this PR and I don't see it yet in development. Did you want to include that too (then title of PR should probably change) or will it be a separate PR? The PR comment implies line is done but it seems not quite.

**Comment by ngan-cassie** [comment]
@huss yes I missed that part. Do you want me to add the changes to this PR and fix the comment instead?

**Comment by huss** [comment]
> @huss yes I missed that part. Do you want me to add the changes to this PR and fix the comment instead?

Yes, I think it would be good to get that fix in. Add it and then edit the title so it shows this too. Okay?

**Review by huss — APPROVED** [review]
Everything looks good and this is ready to merge.

**Pull request merged**
