### PR TITLE
Implementing Test B8

### PR DESCRIPTION
**Pull request by alexis0705**
# Description

I worked on test case B8 with the description: "1 day bars for 15 minute reading intervals and quantity units with +-inf start/end time & kWh as MJ"

Partly Addresses #962 .

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

None.

### CODE REVIEW

**Review by huss — CHANGES_REQUESTED** [review]
Thanks to @alexis0705 for their first contribution to OED. When I locally run the test file changed it is failing. (It also fails on GitHub now that I approved them to run for you.) I believe the issue is that the units and conversions needed are not all defined. I suggest you look at test L10 in src/server/test/web/readingsLineMeterQuantity.js since it uses the same units.

**Comment by alexis0705** [comment]
Hi @huss , thanks for your advise! I have changed my code.

**Comment by alexis0705** [comment]
Hello, I included the following line at the beginning of readingsBarMeterQuantity.js: const Unit = require('../../models/Unit');

During the GitHub test run, I faced a syntax error, highlighting, "SyntaxError: Identifier 'unit' has already been declared." Interestingly, on my local machine, the removal of this line triggers a "ReferenceError: Unit is not defined."

I'm uncertain about whether to retain or remove this line.

**Comment by huss** [comment]
> Hello, I included the following line at the beginning of readingsBarMeterQuantity.js: const Unit = require('../../models/Unit');
> 
> During the GitHub test run, I faced a syntax error, highlighting, "SyntaxError: Identifier 'unit' has already been declared." Interestingly, on my local machine, the removal of this line triggers a "ReferenceError: Unit is not defined."
> 
> I'm uncertain about whether to retain or remove this line.

@alexis0705 I believe the issue is that a recent merge into development added the same include but it was in a slightly different place in the file. I merged the latest development into your PR. It works fine locally and when I push it out to GitHub to your PR it now passes all tests. I'll try to get to the formal review of your changes soon.

**Comment by huss** [comment]
Review of the code found it is all good and running found it works correctly. Congratulations to @alexis0705 on their first accepted contribution.

**Review by huss — APPROVED** [review]

**Comment by alexis0705** [comment]
Thanks to Mustafa Evgin Demirci and John Mikko Velasquez for their support and collaboration. Looking forward to more great teamwork!

**Comment by JohnMikko27** [comment]
Awesome work guys!

**Comment by Evolancer02** [comment]
It was a beneficial experience all around. Thank you guys for being my team partners!

**Pull request merged**
