### PR TITLE
Display start and end times for compare graph

### LINKED ISSUE #477: Line/bar/compare graph x point value and label
The case of meters is fixed by PR #670; case of groups by PR #680: `src/client/app/containers/LineChartContainer.ts` sets `timeReading` to the start time of the point and then uses it as the x value in the graph (both meter and group loop). Given the range of a time can vary and we already show an entire day as a point in many graphs, I wonder if we should make the x value the average of the start & end time so it is in the middle of the range. I think that would place it in a better spot on the graph and be clearer to users as the boundary between the averaging would be between two adjacent points in most cases. In the case of aggregated data, the time should be in the middle of the range the average was created from. Relates to #476.

PR #680 fixed this: In the cases of bar graphs, the day shows two days. This may be due to #476 but that is unclear. It should be labeled with the day it actually represents and only one day. When you look at a week, the label actually shows 8 days where one day overlaps one day on each end of the range. It really should be 7 days in total (so the difference in the dates in the same month is 6). It should be the days that the bar actually represents in meter data. 4 weeks is similar. Basically, there is one too many days on each bar label and the first day should be removed.

Compare graphs do not have an issue that is seen in the label but I think we should show the date/time range that the bars represent so it is clear to the user. See #478 for why may need to label each one separately if the range varies.

### PR DESCRIPTION
**Pull request by ngan-cassie**
# Description

Fixes #477 but completing the last item to do in the issue.

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

I tried loading test data but it threw an error at the end when I checked whether the readings were moved successfully. Perhaps you could help me with this. Here's the terminal output:
[issue with using test data.txt](https://github.com/OpenEnergyDashboard/OED/files/8000084/issue.with.using.test.data.txt)

Hopefully this compare graph fix can close the issue.

### CODE REVIEW

**Comment by huss** [comment]
Thanks to @ngan-cassie for this pull request. During review, I realized there were two issues that we found but not part of the original PR work. I have pushed changes to address them:

1. I should have asked for two date ranges instead of one because the last and this bars in each comparison graph have different time ranges. I also adjusted the look to be consistent with bar graphs (not what @ngan-cassie was asked to do so my fault).
2. There was a performance and bug issue with the end time in Redux state. The changes made the bug be clear. See the last commit for what was up.

I ask that @ngan-cassie review my changes to see if they approve or think more changes would be appropriate.

**Comment by huss** [comment]
For unknown reasons, my last two pushes to ngan PR branch are not showing up here. They were just attempts to get the tests to fire. Also, GitHub Actions did not trigger on the last commit that is showing up. The checks do work on my machine. Unsure why this is all happening.

**Comment by ngan-cassie** [comment]
@huss  the changes look good to me. I don't have any other suggestion. Thank you for the code!

**Review by huss — APPROVED** [review]
The changes look good and run fine for me. The ones I made were looked at by @ngan-cassie. The PR is fine and ready to merge.

**Pull request merged**
