### PR TITLE
Fix issues found with recent PRs

### PR DESCRIPTION
**Pull request by spearec**
- Fix issue with not resetting state after finishing Cik/DB update
- fix issues with button theme capitalization

### CODE REVIEW

**Comment by spearec** [comment]
One thing to note in this PR - some of the buttons were changed to use `color` instead of `variant`, as these were using the syntax for the wrong bootstrap package. This is going to be fully fixed as per #903, but the changes here are a temporary patch for 1.0.

**Review by huss — APPROVED** [review]
Thanks, again, to @spearec for addressing these issues that were an issue for v1.0. The changes look good and testing shows it addressed the desired issues.

**Comment by huss** [comment]
> One thing to note in this PR - some of the buttons were changed to use `color` instead of `variant`, as these were using the syntax for the wrong bootstrap package. This is going to be fully fixed as per #903, but the changes here are a temporary patch for 1.0.

I see that some use color but the changes listed for this PR do not show any as changes from this PR. Am I missing something?

**Comment by spearec** [comment]
> > One thing to note in this PR - some of the buttons were changed to use `color` instead of `variant`, as these were using the syntax for the wrong bootstrap package. This is going to be fully fixed as per #903, but the changes here are a temporary patch for 1.0.
> 
> I see that some use color but the changes listed for this PR do not show any as changes from this PR. Am I missing something?

Sorry if that was unclear - I meant that the issues with some buttons using `color` and others using `variant` is going to be fixed in my work on #903. This PR just fixes a couple of instances of it, but the main migration to using reactstrap is something that will happen later.

**Pull request merged**
