### PR TITLE
Fixing 3D axis labels

### LINKED ISSUE #1194: standardize how graphics get language aware times
### Is your feature request related to a problem? Please describe.

Different parts of the code seem to use different methods to get date aware labeling. Two for hover text are:

- src/client/app/components/ThreeDComponent.tsx uses moment (``dateTS.format(moment.localeData().longDateFormat('L').replace(/YYYY/g, 'YY'))``).
- src/client/app/redux/selectors/lineChartSelectors.ts uses ``timeReading.format('ddd, ll LTS')``

There may be other ways in other places.

### Describe the solution you'd like

OED should decide the best way and consistently use that (maybe by centralizing the code).

### Describe alternatives you've considered

Leave as is but the format may vary.

### Additional context

None

### PR DESCRIPTION
**Pull request by ianLewis8**
# Description

In order to standardize language aware times, the only one I noticed that was unique from the others was the 3D component.

The main reason for this was that the tick marks on the graph would overlap with the graph title and lines due to the axis labels being too long.

In order to fix this, I added a 'tickangle' to the y-axis of the graph that allowed the ticks to display horizontally and thus have more space. I also changed the format statement of this axis to use the same as other charts which was dateTS.format('YYYY-MM-DD HH:mm:ss').

Note that the issue describes another scenario where timeReading.format('ddd, ll LTS') is used. However, this is the standard when adjusting the vertical axis which is supposed to be different from the one I changed.

After adding these changes, the y-axis would display times for a small number of days. I fixed this by adding a few if-else statements that specify the number of ticks and tick interval for a few limited cases and then set to default for all other cases.

Fixes #1194 

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

No limitations to be noted.

### CODE REVIEW

**Review by huss — COMMENTED** [review]
Thanks to @ianLewis8 for this work. Overall, it works well and I like it. I have one small question. When you zoom in to limited days, the axis shows the time of day. With 3D another axis is showing/graphing the time across the day so the date axis should only be the date in an ideal case. Would it be easy to only show the date and year on this axis?

**Comment by ianLewis8** [comment]
Yes I can do that

**Comment by ianLewis8** [comment]
I managed to resolve the issue with the yaxis showing time of day on limited number of days. Let me know if it looks good to you.

**Comment by huss** [comment]
Thanks to @ianLewis8 for figuring this out. I know it was tricky and I appreciate your efforts. Everything looks good.

**Review by huss — APPROVED** [review]
All good.

**Pull request merged**
