### PR TITLE
Change logo

### PR DESCRIPTION
**Pull request by LucasFares**
Replaced logo with blue gradient with simple black and white version.

### CODE REVIEW

**Comment by huss** [comment]
Can someone explain why the color one is an issue? We have color in many
ways on our site so I wanted to better understand. It does not seem to make
it much harder to read for me.

**Comment by LucasFares** [comment]
While the color one isn't an issue per se, we think the black and white version looks nicer.

**Comment by johndiiorio** [comment]
I would also recommend either removing or updating logo_vertical.png, found in the same directory. I don't believe it is used anywhere, but it could be nice to have.

**Comment by LucasFares** [comment]
As far as I can tell, logo_vertical.png was only used to create the favicon. Consistency would be great. Can someone convert the favicon to grayscale? We don't have access to the black and white version of logo_vertical.png so we can't use that to create a new favicon.

**Comment by huss** [comment]
I want to discuss the logo at the meeting before we finalize this. We need
to make a team decision because we should stick with what we choose.

**Comment by johndiiorio** [comment]
This PR is messed up, and a new one will be made shortly.

**Pull request closed without merging**
