### PR TITLE
Create Test LG6

### PR DESCRIPTION
**Pull request by Michael-Kowata**
# Description
@Michael-Kowata @Kyongsu729 @mflores6140
Added Test LG6. Added a csv file for the expected line group. 

Fixes #962

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

N/A

### CODE REVIEW

**Comment by huss** [comment]
Thanks to @Michael-Kowata for this pull request. Could you please help with the following:

- Could you make the title of the pull request reflect that it is for test case LG6.
- The box in the description is not checked for all contributors signing the CLA. The description should list all the authors names too. I also don't see a record of signed CLAs by the people I could determine contributed (let me know if my records are off).
- Please do the other items indicated for the description (also on the developer help pages).
- I did quickly look at the code and it has units and conversions arrays below the test. These are not needed as they are part of the test code. I will do a full reading once all items are in place.

Let me know if you need anything.

**Comment by Michael-Kowata** [comment]
Hey Huss, I apologize for the previous pull request. It's been updated now.

**Comment by huss** [comment]
Everything but the CLA looks good. According to my records, @Michael-Kowata @Kyongsu729 & @mflores6140 have not agreed to the CLA (see link in description). Please agree or let me know that my records are wrong.

**Comment by Michael-Kowata** [comment]
We filled out the CLA form. Let us know if there is anything else we need to do.

**Review by huss — APPROVED** [review]
Thanks to @Michael-Kowata @Kyongsu729 & @mflores6140 for their first contribution to OED. Review found no issues so this is ready to merge. Congratulations on your first accepted code.

**Pull request merged**
