### PR TITLE
Bugfix for loss of map graph display when in mobile

### LINKED ISSUE #1347: lose parts of map on narrow screen
### Describe the bug

If the screen is narrow (at least relative to height) then the map is clipped so part is not shown. There is no scroll to horizontally move the map over. When it is too short you can scroll.

### To Reproduce

1. Use the standard Happy Place map. 
2. Go to the map graphic page.
3. Select this map.
4. It probably looks fine on a normal monitor. Use the web browser tools to change so it is acting as a narrow screen such as a cell phone. You should see the issue. If you rotate the screen via the tools it is then okay as described.

### Expected behavior

User should be able to scroll as they can vertically.

### Screenshots

Screenshot 2024-09-25 131808

### Additional context

I don't think this relates to the fixed aspect/size of 300x500 in maps that should be generalized at some time. If it is then it will be a bigger task. It is unknown how to fix this.

### PR DESCRIPTION
**Pull request by tien-han**
# Description
This bug fix removes the styling `alignItems: 'center'` from the `div` wrapper around the `PlotNavComponent`, which displays  the graphs in the application. With this change, the entire map should be available via scrolling.

Explanation for bug:
The styling did not affect other maps as they were drawn using `Plot` while considering the viewport's width and height in terms of percentages (100% of width and height). The styling caused this bug for map graphs because an image is used (which is not adjusted to the viewport's height and width), and the styling caused the "start" of the map to be at the center.

Fixes #1347 

## Type of change
N/A
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist
- [x] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [N/A] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.org/developer/cla/) and each author is listed in the Description section.

## Limitations
No limitations

## Manual Tests Done
I manually tested the app's behavior pre and post fix for both desktop and mobile viewport, considering:
1.  Line graphs still display properly.
2. Bar graphs still display properly.
3. Compare graphs still display properly.
4. Radar graphs still display properly.
5. Map graphs now display properly.
6. Navigating between graphs and the Menu appears to be working properly.

Note: Happy to provide screenshots of all other maps still working properly, but will only upload the working map view to start with unless more is requested.

https://github.com/user-attachments/assets/4150c567-43bd-49ed-a599-c827083b597d

### CODE REVIEW

**Comment by tien-han** [comment]
Note:  I have manually tested that this change will fix the issue and will not break any other existing feature but will move this PR's status from draft -> review when my teammates can confirm the same on their local development environments.

**Comment by cmatthews444** [comment]
https://github.com/user-attachments/assets/9ddc9bab-7fda-4990-b424-d8c30f2853c4

**Comment by SageMar** [comment]
Here is a video of it working on my Windows machine in Firefox browser as well: 

https://github.com/user-attachments/assets/cc2a7deb-50f1-4b2b-875d-99f2f0815b96

**Review by huss — APPROVED** [review]
Thanks to @tien-han, @cmatthews444 & @SageMar for another contribution to OED. This is a simple but effective fix for the issue. Review found no issues and I also tested by using the web browser Responsive Design Mode where all worked well. I've never had a team supply video of the running changes and they also demonstrates that all is working well. Congratulations on another merged PR.

**Pull request merged**
