### PR TITLE
Update to Readings API testing

### PR DESCRIPTION
**Pull request by MikeLimpus**
# Description
This PR overhauls src/server/test/readings.js to enable tests of multiple values using CSV files generated with a spreadsheet. Primarily, it introduces a set of functions to form a testing jig which should accelerate and simplify writing tests for the readings web API. These functions: 

- Insert units, conversions, meters, and optionally groups into the database using the new functions in PR #827 
- Read and parse CSV files to prepare the expected readings that Chai will compare against the actual readings
- Compare readings from the API against a CSV file
- Generate timestamps to simplify the API call query parameters

This jig is intended to allow other developers to create tests rapidly. It may also be used as a basis for other test files to handle multiple data points in testing.

Some tests are written using the jig, but there are many more tests that should be written, as well as corresponding CSV files for these tests. 

The previous tests were also expanded and given their own describe block in the test file.  

Partly Addresses #698

## Type of change

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update
This change correlates with the testing DevDocs update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

More tests should be written using the expected values CSVs from the DevDocs. The tests should check varied reading intervals (15 minutes is the only interval tested currently). Varied unit types should be tested. Only line meters are tested right now; bar charts and groups should also be tested. These are all contingent on the creation of new CSV files and should work with the test jig.

### CODE REVIEW

**Comment by MikeLimpus** [comment]
Currently failing test script, possibly due to the database being modified by another test. The tests pass when run on their own.

**Comment by MikeLimpus** [comment]
src/server/test/routes/unitReadingsRouteTests.js was using sinon to modify the methods which make up the backend of the readings API without restoring them. This should be resolved now. Recommend a pass is made in the test codebase to ensure that any other use of sinon stubs are restored to ensure this doesn't happen again.

**Comment by huss** [comment]
I updated the PR for a couple of items rather than leaving them to @MikeLimpus due to how long all this took:

1.  Uncommented the flow/raw tests in the code because I added the needed expected CSV files.
2. Merged in development (thanks to @MikeLimpus for doing it recently) to get a very recent update and only list the actual files changed in the PR.

The "successfully creates a user" in usersTest.js was failing. This had nothing directly to do with this PR but began showing up because of changes made. I worked on them and they got mixed in with this PR code so are included. While looking into why, I addressed several items:

1.  A logic issue that almost never arises where an unusual end of the test left the DB in an unusual state and then the next time failed if this was the only test run. Fixed with note in code.
3. Put getConnection() at start of tests as described. This may not be necessary.
4. Fixed bug with missing await in OED production code that was main cause of test failing.
5. Don't ignore duplicate users where create one. map tests had minor issues with the code because this was done. Updated how users are created to test if exist so this error should not occur and will not catch it if it does.
6. Routed error and displayed to user when they have an error in creating a user. This is mostly due to a duplicate user.
7. Changed error notifications to stay for 15 seconds instead of 3. I think it is better to give the user time to see these and they can close sooner if they want. Success notifications are still only 3 seconds.
8. Changed TranslatedString type from a combination of two types to only string. This makes the code easier to deal with. As far as I can tell this does not cause an issue. I left a TODO to simplify the type if this is not an issue that anyone sees.
9. User getByEmail() now returns null if there is no user rather than generating an error. This mimics other places in the code for getting a single item. Updated uses to be compatible and made messages output clearer that this was the reason.

**Comment by huss** [comment]
Thanks to @MikeLimpus for their first PR and doing very nice work in addressing this issue. The code worked fine expected for unexpected issues outside this work. Thanks for fixing the sinon issue. I searched the code and did not find any more uses.

I'm sorry it took so long to finish this but figuring out the issues outside what was the original PR took some time.

This PR is ready to merge.

**Review by huss — APPROVED** [review]
Everything is working fine. The other comments address issues that were solved.

**Pull request merged**
