### PR TITLE
Added test case CG3

### PR DESCRIPTION
**Pull request by Unknown31414652**
# Description

Added test CG3 from design docs testing.md
Partly addresses [#962](https://github.com/OpenEnergyDashboard/OED/issues/962)

## Type of change
- [X] Note merging this changes the database configuration.
- [X] This change requires a documentation update

## Checklist
- [X] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [X] I have removed text in ( ) from the issue request
- [X] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.org/developer/cla/) and each author is listed in the Description section.

##Note
I am part of CodeDay doing this as a micro-internship with Shubham Waldiya

### CODE REVIEW

**Comment by huss** [comment]
@Unknown31414652 Did you do this work alone or with a team? If a team, could you let me know the team members to verify the CLA is signed by all of them. Thanks.

**Review by huss — APPROVED** [review]
Thanks to @Unknown31414652 for this pull request. Review and testing found it works as desired. It can be merged once my CLA comment is addressed.

**Comment by Unknown31414652** [comment]
My group member Shubham Waldiya signed the CLA

**Comment by huss** [comment]
Congratulations to @Unknown31414652 & @HiThere-12345 on your first accepted contribution to OED.

**Pull request merged**
